Repository cybersemics/em, pull requests merged in 2025-05, with the labels that each got.

#2874 Feature: Add Command Menu to mobile devices
  panda.config.ts
  src/@types/Command.ts
  src/@types/CommandType.ts
  src/@types/State.ts
  src/actions/setCursor.ts
  src/actions/toggleDropdown.ts
  src/commands/indent.ts
  src/commands/outdent.ts
  src/components/AppComponent.tsx
  src/components/Bullet.tsx
  src/components/BulletEllipsis.tsx
  src/components/CommandMenu/CommandMenuPanel.tsx
  src/components/CommandMenu/PanelCommand.tsx
  src/components/CommandMenu/PanelCommandGrid.tsx
  src/components/CommandMenu/PanelCommandGroup.tsx
  src/components/CommandMenu/PanelCommandHeader.tsx
  src/components/icons/CloseIcon.tsx
  src/components/icons/EllipsisIcon.tsx
  src/recipes/panelCommandGroupRecipe.ts
  src/recipes/panelCommandRecipe.ts
  src/util/initialState.ts
Labels: feature

#2891 Multiselect: Undo/redo executeCommandWithMulticursor all at once
  src/@types/State.ts
  src/actions/index.ts
  src/actions/setIsMulticursorExecuting.ts
  src/commands/__tests__/undo-redo.ts
  src/redux-enhancers/undoRedoEnhancer.ts
  src/util/executeCommand.ts
  src/util/initialState.ts
Labels: bug

#2934 Divider is not highlighted when it has the cursor
  src/components/Divider.tsx
  src/e2e/puppeteer/__tests__/__image_snapshots__/render-thoughts/font-size-18-default-divider-1.png
  src/e2e/puppeteer/__tests__/__image_snapshots__/render-thoughts/font-size-18-default-divider-2.png
  src/e2e/puppeteer/__tests__/render-thoughts.ts
Labels: bug

#2937 Replace commandById with static import
  src/commands.ts
  src/components/CommandPalette.tsx
  src/components/EmptyThoughtspace.tsx
  src/components/NoOtherContexts.tsx
  src/components/Tutorial/Tutorial2StepContext1.tsx
  src/components/Tutorial/Tutorial2StepContext1Parent.tsx
  src/components/Tutorial/Tutorial2StepContext1SubThought.tsx
  src/components/Tutorial/Tutorial2StepContext2.tsx
  src/components/Tutorial/Tutorial2StepContext2Parent.tsx
  src/components/Tutorial/Tutorial2StepContext2Subthought.tsx
  src/components/Tutorial/Tutorial2StepContextViewToggle.tsx
  src/components/Tutorial/TutorialStepFirstThought.tsx
  src/components/Tutorial/TutorialStepSecondThought.tsx
  src/components/Tutorial/TutorialStepSecondThoughtEnter.tsx
  src/components/Tutorial/TutorialStepSubThought.tsx
  src/components/Tutorial/index.tsx
Labels: refactor
